const $ = id => document.getElementById(id);
const KEY = 'stormkeeper.v17';
const esc = s => String(s ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtMod = n => Number(n) >= 0 ? `+${Number(n)}` : `${Number(n)}`;

const EQUIPMENT_PACKAGES={
  Barbarian:[['Frontline','Greataxe or martial melee weapon • two handaxes • explorer-style pack'],['Guardian','Martial melee weapon • shield • four javelins • explorer-style pack']],
  Bard:[['Performer','Rapier • entertainer-style instrument • light armor • travel pack'],['Skilled Traveler','Shortsword • light crossbow • instrument • travel pack']],
  Cleric:[['War Priest','Mace or warhammer • shield • light/medium armor • priest-style pack'],['Holy Caster','Light/medium armor • shield • simple weapon • holy symbol • priest-style pack']],
  Druid:[['Warden','Wooden shield • scimitar or simple weapon • hide/leather armor • explorer-style pack'],['Wayfarer','Quarterstaff • shield • leather/hide armor • explorer-style pack']],
  Fighter:[['Heavy Frontliner','Martial weapon • shield • heavy/medium armor when proficient • explorer-style pack'],['Two-Weapon Warrior','Two martial weapons • light/medium armor • ranged backup • explorer-style pack']],
  Monk:[['Wandering Adept','Simple weapon or shortsword • artisan or musical tool • traveler-style pack'],['Striker','Shortsword • simple weapon • traveler-style pack']],
  Paladin:[['Holy Vanguard','Martial weapon • shield • heavy armor when proficient • priest-style pack'],['Devoted Duelist','Martial weapon • shield or second weapon • heavy/medium armor when proficient']],
  Ranger:[['Hunter','Two martial/ranged weapons • leather armor • arrows/bolts • explorer-style pack'],['Scout','Two light weapons • ranged weapon • leather armor • dungeoneer-style pack']],
  Rogue:[['Skirmisher','Rapier or shortsword • shortbow • leather armor • burglar-style pack'],['Infiltrator','Two light weapons • shortbow • leather armor • thief-style pack']],
  Sorcerer:[['Arcane Wanderer','Light weapon • arcane focus • simple travel pack'],['Spellblade','Light weapon • arcane focus • scholar-style pack']],
  Warlock:[['Pact Initiate','Light weapon • arcane focus • scholar-style pack'],['Occult Traveler','Simple weapon • light armor when proficient • arcane focus • traveler-style pack']],
  Wizard:[['Scholar','Quarterstaff or dagger • spellbook/focus • scholar-style pack'],['Battle Mage','Quarterstaff or dagger • spellbook/focus • explorer-style pack']]
};
const BACKGROUND_GEAR={
  Soldier:'A martial keepsake, insignia or trophy, common clothing, and a modest pouch of coin.',
  Acolyte:'A holy symbol, prayer book or devotional item, vestments, and a modest pouch of coin.',
  Criminal:'A small set of covert tools, dark common clothing, and a modest pouch of coin.',
  'Folk Hero':'A remembered tool or trophy from home, common clothing, and a modest pouch of coin.',
  Sage:'Writing materials, notes or books, scholarly clothing, and a modest pouch of coin.',
  Hermit:'A small herbalist or devotional kit, simple clothing, and a modest pouch of coin.',
  Noble:'Fine clothes, a signet or keepsake, and a modest pouch of coin.',
  Outlander:'A survival keepsake, traveler clothing, and a modest pouch of coin.',
  Sailor:'A sailor keepsake, common clothing, and a modest pouch of coin.',
  'Guild Artisan':'Artisan tools, work clothing, and a modest pouch of coin.',
  Entertainer:'A costume or performance prop, common clothing, and a modest pouch of coin.',
  Urchin:'A small keepsake, worn clothing, and a modest pouch of coin.'
};
const FALLBACK = {
  species:['Orc','Human','Elf','Dwarf','Halfling','Gnome','Half-Elf','Half-Orc','Tiefling'],
  backgrounds:['Soldier','Acolyte','Criminal','Folk Hero','Sage','Hermit','Noble','Outlander','Sailor','Guild Artisan','Entertainer','Urchin'],
  classes:{
    Cleric:{hitDie:8,primaryAbility:'Wisdom',savingThrows:['Wisdom','Charisma'],armor:['Light armor','Medium armor','Shields'],weapons:['Simple weapons'],features:{1:['Spellcasting','Divine Domain'],2:['Channel Divinity','Turn Undead']},subclasses:{'Tempest Domain':{features:{1:['Bonus Proficiencies','Wrath of the Storm'],2:['Channel Divinity: Destructive Wrath']},proficiencies:['Martial weapons','Heavy armor']}}},
    Druid:{hitDie:8,primaryAbility:'Wisdom',savingThrows:['Intelligence','Wisdom'],armor:['Light armor','Medium armor (nonmetal)','Shields (nonmetal)'],weapons:['Clubs','Daggers','Darts','Javelins','Maces','Quarterstaffs','Scimitars','Sickles','Slings','Spears'],features:{1:['Druidic','Spellcasting'],2:['Wild Shape','Druid Circle']},subclasses:{'Circle of the Shepherd':{features:{2:['Speech of the Woods','Spirit Totem']}}}}
  },
  alignments:['Lawful Good','Neutral Good','Chaotic Good','Lawful Neutral','True Neutral','Chaotic Neutral','Lawful Evil','Neutral Evil','Chaotic Evil'],
  deities:['Perun','Pelor','Bahamut','Corellon','Moradin','Selûne','Tyr','Tempus','The Raven Queen','None / Custom'],
  armor:['None','Leather Armor','Studded Leather','Hide','Chain Shirt','Scale Mail','Breastplate','Half Plate','Ring Mail','Chain Mail','Splint','Plate','Shield'],
  weapons:['Club','Dagger','Quarterstaff','Spear','Light Crossbow','Mace','Sickle','Scimitar','Shortsword','Javelin','Handaxe','Light Hammer','Battleaxe','Longsword','Warhammer','Maul','Greatsword','Greataxe','Rapier','Shortbow','Longbow']
};
let RULES={classes:{},species:{},backgrounds:{},spells:{},conditions:[]};
let MECH={abilityNames:['Strength','Dexterity','Constitution','Intelligence','Wisdom','Charisma'],armor:{},weapons:{}};
let PROGRESSION={}; let CATALOG={};
let state=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('stormkeeper.v15')||localStorage.getItem('stormkeeper.v14')||localStorage.getItem('stormkeeper.v13')||'{"characters":[],"settings":{"inlineRules":false}}');
if(!state.settings)state.settings={inlineRules:false}; if(!Array.isArray(state.characters))state.characters=[];
let draft={}; let wizardPage=0; let detailReturn=1; let openId=null;
const UNLOCK={Cleric:1,Druid:2,Fighter:3,Ranger:3,Rogue:3,Wizard:2,Sorcerer:1,Warlock:1,Bard:3,Paladin:3,Barbarian:3,Monk:3};

function toast(msg){const t=$('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
async function loadJSON(file,fallback){try{const r=await fetch(`${file}`);if(!r.ok)throw 0;return await r.json()}catch{return fallback}}
async function loadData(){
  const [classes,species,backgrounds,spells,conditions,mechanics,progression,catalog]=await Promise.all([
    loadJSON('classes.json',FALLBACK.classes),loadJSON('species_rules.json',{}),loadJSON('background_rules.json',{}),loadJSON('spells.json',{}),loadJSON('conditions.json',[]),loadJSON('mechanics.json',MECH),loadJSON('progression.json',{}),loadJSON('catalog.json',{})
  ]);
  RULES={classes:classes||FALLBACK.classes,species:species||{},backgrounds:backgrounds||{},spells:spells||{},conditions:conditions||[]};
  MECH=mechanics||MECH;PROGRESSION=progression||{};CATALOG=catalog||{};
}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id)?.classList.add('active');scrollTo(0,0)}
function fillElement(e,values,blank='Choose…',current=''){if(!e)return;e.innerHTML=`<option value="">${esc(blank)}</option>`+values.map(v=>`<option value="${esc(v)}"${v===current?' selected':''}>${esc(v)}</option>`).join('')}
function fill(id,values,blank='Choose…',current=''){fillElement($(id),values,blank,current)}
function classDef(cls){return RULES.classes?.[cls]||FALLBACK.classes[cls]||{}}
function ruleInfo(type,name){if(type==='class')return classDef(name);if(type==='species')return RULES.species?.[name]||{};if(type==='background')return RULES.backgrounds?.[name]||{};return {}}
function classLevel(c,cls){if(!cls)return 0;if(cls===c.class1)return Number(c.class1Level||0);if(cls===c.class2)return Number(c.class2Level||0);return 0}
function normalizeLevels(c){let total=Math.max(1,Math.min(20,Number(c.level||1)));let a=Number(c.class1Level||0),b=Number(c.class2Level||0);if(!c.class2){a=total;b=0}else{a=Math.max(1,a);b=Math.max(1,b);if(a+b!==total)b=Math.max(1,total-a);if(a+b!==total)a=Math.max(1,total-b)}c.class1Level=a;c.class2Level=b;c.level=a+b;return c}
function subclassUnlockLevel(cls){const d=classDef(cls);if(d.features){const hits=Object.entries(d.features).filter(([lvl,fs])=>fs.some(f=>/domain|circle|subclass|archetype|tradition|college|oath|patron|school|path|way/i.test(f))).map(([lvl])=>+lvl);if(hits.length)return Math.min(...hits)}return UNLOCK[cls]||99}
function subclassOptions(cls){const d=classDef(cls);return d.subclasses?Object.keys(d.subclasses):[]}
function armorAllowed(c,n){if(!n)return false;if(n==='None'||n==='Leather Armor'||n==='Studded Leather')return true;const hasC=c.class1==='Cleric'||c.class2==='Cleric',hasD=c.class1==='Druid'||c.class2==='Druid',temp=c.subclass1==='Tempest Domain'||c.subclass2==='Tempest Domain';if(n==='Shield')return hasC||hasD;if(hasD&&['Scale Mail','Chain Shirt','Breastplate','Half Plate','Ring Mail','Chain Mail','Splint','Plate'].includes(n))return false;if(['Ring Mail','Chain Mail','Splint','Plate'].includes(n))return temp;return hasC||hasD}
function weaponAllowed(c,n){if(!n)return false;const simple=['Club','Dagger','Quarterstaff','Spear','Light Crossbow','Mace','Sickle','Javelin','Light Hammer'];const druid=['Club','Dagger','Javelin','Mace','Quarterstaff','Scimitar','Sickle','Spear'];const martial=['Scimitar','Shortsword','Handaxe','Battleaxe','Longsword','Warhammer','Maul','Greatsword','Greataxe','Rapier','Longbow','Shortbow'];const hasC=c.class1==='Cleric'||c.class2==='Cleric',hasD=c.class1==='Druid'||c.class2==='Druid',temp=c.subclass1==='Tempest Domain'||c.subclass2==='Tempest Domain';if(hasC||hasD)return simple.includes(n)||druid.includes(n)||(temp&&martial.includes(n));return true}

function render(){const list=$('list'),count=$('characterCount');if(count)count.textContent=`${state.characters.length} character${state.characters.length===1?'':'s'}`;if(!list)return;list.innerHTML=state.characters.length?state.characters.map(c=>{normalizeLevels(c);const subs=[c.subclass1,c.subclass2].filter(Boolean).join(' • ');return `<article class="character" data-id="${c.id}"><div class="character-top"><b>${esc(c.name||'Unnamed Character')}</b><span class="pill">Lvl ${c.level}</span></div><div class="muted">${esc(c.species||'—')} • ${esc(c.class1||'—')} ${classLevel(c,c.class1)||1}${c.class2?` / ${esc(c.class2)} ${classLevel(c,c.class2)}`:''}</div>${subs?`<div class="subclass-chip">${esc(subs)}</div>`:''}</article>`}).join(''):`<div class="card empty-party"><h3>No characters yet</h3><p class="muted">Forge your first character.</p></div>`;list.querySelectorAll('.character').forEach(x=>x.onclick=()=>openSheet(x.dataset.id));save()}
function saveCharacter(c){const i=state.characters.findIndex(x=>x.id===c.id);if(i>=0)state.characters[i]={...c};save()}

// ---------- Character creation wizard ----------
const pages=[
  ['IDENTITY','Name your hero','Start with the person behind the sheet.'],
  ['SPECIES','Choose your species','Open a choice to read its traits and notes before selecting it.'],
  ['BACKGROUND','Choose your background','See the skills, tools, and feature before you commit.'],
  ['PRIMARY CLASS','Choose your primary class','Read the class overview, proficiencies, level features, and subclass paths.'],
  ['LEVEL','Set your character level','Multiclassing is based on levels in each class.'],
  ['SECOND CLASS','Stay single-classed or multiclass','If you multiclass, read the second class before choosing it.'],
  ['WORLD','Shape your story','Choose alignment and deity.'],
  ['EQUIPMENT','Prepare for adventure','Choose filtered gear and your ability-score method.']
];
function updateWizardHead(){const p=pages[wizardPage];$('wizardTitle').textContent=p[1];$('wizardHint').textContent=p[2];$('wizardStepLabel').textContent=`Step ${wizardPage+1} of ${pages.length}`;$('wizardProgress').style.width=`${((wizardPage+1)/pages.length)*100}%`}
function choiceCards(type,items){return `<div class="choice-grid">${items.map(name=>`<button class="choice-card" data-choice="${esc(name)}"><span class="choice-kicker">${esc(type)}</span><strong>${esc(name)}</strong><span>View details →</span></button>`).join('')}</div>`}
function detailHtml(type,name){const v=ruleInfo(type,name);let h=`<div class="detail-hero"><div class="detail-icon">${type==='class'?'⚔':type==='species'?'🧬':'📜'}</div><div><div class="eyebrow">${esc(type)}</div><h2>${esc(name)}</h2></div></div>`;
  if(type==='class'){
    h+=`<div class="detail-grid"><div><b>Hit Die</b><span>d${esc(v.hitDie||8)}</span></div><div><b>Primary Ability</b><span>${esc(v.primaryAbility||'—')}</span></div><div><b>Saving Throws</b><span>${esc((v.savingThrows||[]).join(', ')||'—')}</span></div><div><b>Armor</b><span>${esc((v.armor||[]).join(', ')||'—')}</span></div><div><b>Weapons</b><span>${esc((v.weapons||[]).join(', ')||'—')}</span></div></div>`;
    h+=`<section class="detail-section"><h3>Class features</h3><div class="feature-list">${Object.entries(v.features||{}).sort((a,b)=>+a[0]-+b[0]).map(([lvl,fs])=>`<div><b>Level ${lvl}</b> — ${esc(fs.join(', '))}</div>`).join('')||'<div>No class features are currently loaded.</div>'}</div></section>`;
    const subs=Object.keys(v.subclasses||{});if(subs.length)h+=`<section class="detail-section"><h3>Subclass paths</h3><p class="muted">You do <b>not</b> choose a subclass here. You will choose one when you reach the class's unlock level.</p><div class="mini-list">${subs.map(s=>`<span>${esc(s)}</span>`).join('')}</div></section>`;
  } else if(type==='species'){
    h+=`<section class="detail-section"><h3>Traits</h3><ul>${(v.features||[]).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>No detailed traits are loaded for this option.</li>'}</ul>${v.notes?`<p class="muted">${esc(v.notes)}</p>`:''}</section>`;
  } else {
    h+=`<section class="detail-section"><h3>Background benefits</h3>${v.skills?.length?`<p><b>Skills:</b> ${esc(v.skills.join(', '))}</p>`:''}${v.toolProficiencies?.length?`<p><b>Tools:</b> ${esc(v.toolProficiencies.join(', '))}</p>`:''}${v.feature?`<p><b>Feature:</b> ${esc(v.feature)}</p>`:''}</section>`;
  }return h}
function showDetail(type,name,backPage,onChoose){detailReturn=backPage;const root=$('wizard');root.innerHTML=`<div class="detail-page"><button class="back-btn" id="detailBack">← Back to choices</button>${detailHtml(type,name)}<div class="detail-actions"><button class="btn" id="detailBack2">Not yet</button><button class="primary" id="detailChoose">Choose ${esc(name)} →</button></div></div>`;$('detailBack').onclick=wizardRender;$('detailBack2').onclick=wizardRender;$('detailChoose').onclick=()=>{onChoose();wizardPage=backPage+1;if(backPage===3)wizardPage=4;wizardRender()}}
function wizardRender(){updateWizardHead();const root=$('wizard');let body='';
  if(wizardPage===0)body=`<div class="wizard-intro"><div class="big-rune">⚡</div><div><div class="eyebrow">STEP 1 • IDENTITY</div><h2>Who are you forging?</h2><p>Name and age are kept flexible.</p><input id="wizName" class="hero-input" value="${esc(draft.name||'')}" placeholder="Character name (optional)"><label class="small-field">Age<input id="wizAge" type="number" min="0" value="${esc(draft.age||'')}" placeholder="Optional"></label><button class="primary wizard-next" id="nameNext">Continue →</button></div></div>`;
  if(wizardPage===1)body=`<div class="wizard-copy"><div class="eyebrow">STEP 2 • SPECIES</div><h2>Choose your lineage</h2><p>Nothing is final until you press Choose.</p></div>${choiceCards('Species',Object.keys(RULES.species).length?Object.keys(RULES.species):FALLBACK.species)}`;
  if(wizardPage===2)body=`<div class="wizard-copy"><div class="eyebrow">STEP 3 • BACKGROUND</div><h2>Where did you come from?</h2><p>Read the benefits first, then choose.</p></div>${choiceCards('Background',Object.keys(RULES.backgrounds).length?Object.keys(RULES.backgrounds):FALLBACK.backgrounds)}`;
  if(wizardPage===3)body=`<div class="wizard-copy"><div class="eyebrow">STEP 4 • PRIMARY CLASS</div><h2>What kind of adventurer are you?</h2><p>Tap a class to open its full current Stormkeeper summary.</p></div>${choiceCards('Class',Object.keys(RULES.classes).length?Object.keys(RULES.classes):Object.keys(FALLBACK.classes))}`;
  if(wizardPage===4)body=`<div class="wizard-copy"><div class="eyebrow">STEP 5 • LEVEL</div><h2>How experienced is your hero?</h2><p>Choose total character level. At level 2+, you may choose a second class on the next page.</p></div><div class="level-picker"><label>Total Character Level<select id="wizLevel">${Array.from({length:20},(_,i)=>`<option value="${i+1}"${Number(draft.level||1)===i+1?' selected':''}>${i+1}</option>`).join('')}</select></label><div class="choice-summary"><b>${esc(draft.class1)}</b><span>${esc(classDef(draft.class1).primaryAbility||'—')} primary ability</span></div></div><div class="wizard-actions"><button class="btn" id="wizBack">← Back</button><button class="primary" id="levelNext">Continue →</button></div>`;
  if(wizardPage===5)body=`<div class="wizard-copy"><div class="eyebrow">STEP 6 • SECOND CLASS</div><h2>Stay single-classed or multiclass?</h2><p>Your primary class remains at least level 1. Open a second class to read about it.</p></div>${choiceCards('Second Class',['No second class',...Object.keys(RULES.classes).filter(c=>c!==draft.class1)])}`;
  if(wizardPage===6)body=`<div class="wizard-copy"><div class="eyebrow">STEP 7 • WORLD</div><h2>Set your place in the world</h2><p>These are story choices and can be changed later.</p></div><div class="grid wizard-form-grid"><label>Alignment<select id="wizAlignment"></select></label><label>Deity<select id="wizDeity"></select></label></div><div class="wizard-actions"><button class="btn" id="wizBack">← Back</button><button class="primary" id="worldNext">Continue →</button></div>`;
  if(wizardPage===7)body=`<div class="wizard-copy"><div class="eyebrow">STEP 8 • STARTING EQUIPMENT</div><h2>Choose how you enter the world</h2><p>Stormkeeper recommends starting gear from your primary class, then shows your background gear. Pick a package first, then adjust individual armor or weapon choices if needed.</p></div><div class="review-card"><div class="eyebrow">CLASS RECOMMENDATION</div><h3>${esc(draft.class1||'Class')}</h3><p class="muted">${esc(classDef(draft.class1).primaryAbility||'—')} primary ability • equipment packages below are a quick-start summary.</p></div><div id="packageGrid" class="choice-grid"></div><div class="card" style="margin-top:14px"><div class="eyebrow">BACKGROUND GEAR</div><h3>${esc(draft.background||'Background')}</h3><p class="muted">${esc(BACKGROUND_GEAR[draft.background]||'Use the equipment associated with your selected background.')}</p></div><div class="grid wizard-form-grid"><label>Armor<select id="wizArmor"></select></label><label>Weapon<select id="wizWeapon"></select></label><label class="wide">Ability Score Method<select id="wizStats"><option value="Leave blank — roll at the table">Leave blank — roll at the table</option><option value="Standard Array">Standard Array</option><option value="Point Buy">Point Buy</option></select></label></div><div class="review-card"><div class="eyebrow">READY TO FORGE</div><h3>${esc(draft.name||'Unnamed Character')}</h3><p>${esc(draft.species)} • ${esc(draft.background)} • ${esc(draft.class1)} ${draft.class1Level||draft.level}${draft.class2?` / ${esc(draft.class2)} ${draft.class2Level}`:''}</p><p>${esc(draft.alignment||'—')} • ${esc(draft.deity||'—')}</p><p><b>Package:</b> ${esc(draft.equipmentPackage||'Choose a package')}</p></div><div class="wizard-actions"><button class="btn" id="wizBack">← Back</button><button class="primary" id="forgeBtn">⚡ Forge Character</button></div>`;
  root.innerHTML=body;wireWizard();}
function wireWizard(){
  if(wizardPage===0){$('nameNext').onclick=()=>{draft.name=$('wizName').value.trim();draft.age=$('wizAge').value;wizardPage=1;wizardRender()};return}
  if(wizardPage===1||wizardPage===2||wizardPage===3||wizardPage===5){document.querySelectorAll('.choice-card').forEach(b=>b.onclick=()=>{
    const name=b.dataset.choice;
    if(wizardPage===1)showDetail('species',name,1,()=>draft.species=name);
    if(wizardPage===2)showDetail('background',name,2,()=>draft.background=name);
    if(wizardPage===3)showDetail('class',name,3,()=>{draft.class1=name});
    if(wizardPage===5){if(name==='No second class'){draft.class2='';draft.class2Level=0;draft.class1Level=Number(draft.level||1);wizardPage=6;wizardRender()}else showDetail('class',name,5,()=>{draft.class2=name})}
  });return}
  if(wizardPage===4){$('wizBack').onclick=()=>{wizardPage=3;wizardRender()};$('levelNext').onclick=()=>{draft.level=Number($('wizLevel').value);draft.class1Level=draft.level;draft.class2Level=0;wizardPage=draft.level>1?5:6;wizardRender()};return}
  if(wizardPage===6){fill('wizAlignment',FALLBACK.alignments,'Choose alignment…',draft.alignment);fill('wizDeity',FALLBACK.deities,'Choose deity…',draft.deity);$('wizBack').onclick=()=>{wizardPage=5;wizardRender()};$('worldNext').onclick=()=>{draft.alignment=$('wizAlignment').value;draft.deity=$('wizDeity').value;wizardPage=7;wizardRender()};return}
  if(wizardPage===7){const c={class1:draft.class1,class2:draft.class2,subclass1:'',subclass2:''};const packages=EQUIPMENT_PACKAGES[draft.class1]||[];const pg=$('packageGrid');pg.innerHTML=packages.map((p,i)=>`<button class="choice-card package-card" data-package="${esc(p[0])}"><span class="choice-kicker">${i===0?'Recommended':'Alternative'}</span><strong>${esc(p[0])}</strong><span>${esc(p[1])}</span><span>Use this package →</span></button>`).join('')||`<div class="card"><b>No class package loaded.</b><p class="muted">Choose individual gear below.</p></div>`;pg.querySelectorAll('[data-package]').forEach(b=>b.onclick=()=>{draft.equipmentPackage=b.dataset.package;const p=packages.find(x=>x[0]===b.dataset.package);if(p){if(/shield/i.test(p[1]))draft.armor='Shield';else if(/heavy\/medium|heavy armor|medium armor/i.test(p[1]))draft.armor='Chain Mail';else if(/hide\/leather|leather armor/i.test(p[1]))draft.armor='Leather Armor';else draft.armor='None';if(/greatsword/i.test(p[1]))draft.weapon='Greatsword';else if(/greataxe/i.test(p[1]))draft.weapon='Greataxe';else if(/longbow|shortbow/i.test(p[1]))draft.weapon=/longbow/i.test(p[1])?'Longbow':'Shortbow';else if(/rapier/i.test(p[1]))draft.weapon='Rapier';else if(/shortsword/i.test(p[1]))draft.weapon='Shortsword';else if(/warhammer/i.test(p[1]))draft.weapon='Warhammer';else if(/mace/i.test(p[1]))draft.weapon='Mace';else if(/scimitar/i.test(p[1]))draft.weapon='Scimitar';else if(/quarterstaff/i.test(p[1]))draft.weapon='Quarterstaff';else draft.weapon='Simple Weapon';}wizardRender()});fillElement($('wizArmor'),FALLBACK.armor.filter(x=>armorAllowed(c,x)),'Choose armor…',draft.armor);fillElement($('wizWeapon'),FALLBACK.weapons.filter(x=>weaponAllowed(c,x)),'Choose weapon…',draft.weapon);$('wizStats').value=draft.stats||'Leave blank — roll at the table';$('wizArmor').onchange=e=>draft.armor=e.target.value;$('wizWeapon').onchange=e=>draft.weapon=e.target.value;$('wizStats').onchange=e=>draft.stats=e.target.value;$('wizBack').onclick=()=>{wizardPage=6;wizardRender()};$('forgeBtn').onclick=forgeDraft}}
function forgeDraft(){const total=Number(draft.level||1);if(draft.class2){const b=Math.max(1,total-Number(draft.class1Level||1));draft.class2Level=b;draft.class1Level=Math.max(1,total-b)}else{draft.class1Level=total;draft.class2Level=0}const c={id:Date.now(),name:draft.name||'',age:draft.age||'',species:draft.species||'',background:draft.background||'',class1:draft.class1||'',class2:draft.class2||'',level:total,class1Level:Number(draft.class1Level||total),class2Level:Number(draft.class2Level||0),subclass1:'',subclass2:'',alignment:draft.alignment||'',deity:draft.deity||'',armor:draft.armor||'',weapon:draft.weapon||'',equipmentPackage:draft.equipmentPackage||'',stats:draft.stats||'Leave blank — roll at the table'};normalizeLevels(c);state.characters.push(c);save();render();openSheet(c.id);toast('Character forged')}
function initCreator(){draft={level:1,stats:'Leave blank — roll at the table',equipmentPackage:''};wizardPage=0;wizardRender()}

// ---------- Character sheet ----------
function calculate(c){const lvl=Math.max(1,+c.level||1),pb=2+Math.floor((lvl-1)/4),mods={};for(const n of MECH.abilityNames||[])mods[n]=Math.floor((Number((c.stats||{})[n]??10)-10)/2);const dex=mods.Dexterity||0;const armor=MECH.armor?.[c.armor]||{base:10,dex:true};const ac=Number(armor.base??armor.baseAC??10)+(armor.dex?Math.min(dex,armor.cap??99):0)+(c.armor==='Shield'?2:0);const wis=mods.Wisdom||0;return{pb,mods,ac,initiative:dex,spellDC:8+pb+wis,spellAttack:pb+wis}}
function mechanicsPanel(c){const r=calculate(c);const d=document.createElement('div');d.className='character-card';d.innerHTML=`<h3>Combat Statistics</h3><div class="metric-grid"><div><span>Armor Class</span><strong>${r.ac}</strong></div><div><span>Proficiency</span><strong>+${r.pb}</strong></div><div><span>Initiative</span><strong>${fmtMod(r.initiative)}</strong></div><div><span>Spell Save DC</span><strong>${r.spellDC}</strong></div><div><span>Spell Attack</span><strong>${fmtMod(r.spellAttack)}</strong></div></div><h3>Ability Scores</h3><div class="stat-grid">${(MECH.abilityNames||[]).map(n=>`<div class="stat-tile"><b>${n.slice(0,3).toUpperCase()}</b><strong>${esc((c.stats||{})[n]??'—')}</strong><span>${fmtMod(r.mods[n])}</span></div>`).join('')}</div>`;return d}
function progressionPanel(c){const d=document.createElement('div');d.className='character-card level-panel';const features=[];for(const [cls,lvl] of [[c.class1,classLevel(c,c.class1)],[c.class2,classLevel(c,c.class2)]]){if(!cls)continue;for(let n=1;n<=lvl;n++)for(const f of (classDef(cls).features?.[n]||PROGRESSION[cls]?.levels?.[String(n)]||[]))features.push(`${cls} ${n}: ${f}`)}d.innerHTML=`<div class="level-head"><div><div class="eyebrow">LEVEL PROGRESSION</div><h3>Level ${c.level}</h3></div><button class="primary" id="levelUp">Level Up →</button></div><p class="muted">${esc(c.class1)} ${classLevel(c,c.class1)}${c.class2?` / ${esc(c.class2)} ${classLevel(c,c.class2)}`:''}</p><div class="feature-list">${features.map(f=>`<div>• ${esc(f)}</div>`).join('')||'<div>—</div>'}</div>`;d.querySelector('#levelUp').onclick=()=>levelUp(c);return d}
function subclassPanel(c){const wrap=document.createElement('div');wrap.className='character-card subclass-choice-panel';wrap.innerHTML='<div class="eyebrow">CLASS SPECIALIZATION</div><h3>Subclass Choices</h3><p class="muted">Subclasses appear only when that class reaches its unlock level.</p>';for(const [label,cls,key] of [['Primary',c.class1,'subclass1'],['Second',c.class2,'subclass2']]){if(!cls)continue;const lvl=classLevel(c,cls),unlock=subclassUnlockLevel(cls),opts=subclassOptions(cls),row=document.createElement('div');row.className='subclass-row';if(lvl<unlock)row.innerHTML=`<div><b>${esc(label)} Class: ${esc(cls)}</b><small>Class level ${lvl}. Unlocks at ${unlock}.</small></div><span class="locked-badge">LOCKED</span>`;else{row.innerHTML=`<label><b>${esc(label)} Class: ${esc(cls)} — Level ${lvl}</b><select><option value="">Choose subclass…</option>${opts.map(o=>`<option value="${esc(o)}"${o===c[key]?' selected':''}>${esc(o)}</option>`).join('')}</select></label>`;row.querySelector('select').onchange=e=>{c[key]=e.target.value;saveCharacter(c);renderSheet(c)}}wrap.appendChild(row)}return wrap}
function levelUp(c){if(c.level>=20)return;normalizeLevels(c);if(c.class2){const choice=prompt(`Level up in which class?\n1. ${c.class1} (level ${classLevel(c,c.class1)})\n2. ${c.class2} (level ${classLevel(c,c.class2)})`,'1');if(choice==='2')c.class2Level++;else c.class1Level++}else c.class1Level++;c.level=(c.class1Level||0)+(c.class2Level||0);for(const [cls,key] of [[c.class1,'subclass1'],[c.class2,'subclass2']])if(cls&&c[key]&&classLevel(c,cls)<subclassUnlockLevel(cls))c[key]='';saveCharacter(c);render();renderSheet(c)}
function renderSheet(c){normalizeLevels(c);$('sheetName').textContent=c.name||'Unnamed Character';$('sheetMeta').textContent=[c.species,c.background,`${c.class1} ${classLevel(c,c.class1)}`,c.class2?`${c.class2} ${classLevel(c,c.class2)}`:'',c.subclass1,c.subclass2].filter(Boolean).join(' • ');$('sheetLevel').textContent=c.level;const body=$('sheetBody');body.innerHTML=`<div class="character-card"><h3>Character Overview</h3><p><b>Alignment:</b> ${esc(c.alignment||'—')} &nbsp; <b>Deity:</b> ${esc(c.deity||'—')}</p><p><b>Armor:</b> ${esc(c.armor||'—')} &nbsp; <b>Weapon:</b> ${esc(c.weapon||'—')}</p><p><b>Starting Package:</b> ${esc(c.equipmentPackage||'—')}</p></div>`;body.appendChild(progressionPanel(c));body.appendChild(subclassPanel(c));body.appendChild(mechanicsPanel(c));const eq=document.createElement('div');eq.className='character-card';eq.innerHTML='<h3>Equipment</h3><div class="grid"><label>Armor<select id="sheetArmor"></select></label><label>Weapon<select id="sheetWeapon"></select></label></div>';body.appendChild(eq);fillElement($('sheetArmor'),FALLBACK.armor.filter(x=>armorAllowed(c,x)),'Choose armor…',c.armor);fillElement($('sheetWeapon'),FALLBACK.weapons.filter(x=>weaponAllowed(c,x)),'Choose weapon…',c.weapon);$('sheetArmor').onchange=e=>{c.armor=e.target.value;saveCharacter(c);renderSheet(c)};$('sheetWeapon').onchange=e=>{c.weapon=e.target.value;saveCharacter(c);renderSheet(c)}}
function openSheet(id){const c=state.characters.find(x=>x.id===id);if(!c)return;openId=id;normalizeLevels(c);saveCharacter(c);renderSheet(c);show('sheet')}

// ---------- Rules reference ----------
async function openCatalog(){const rules=$('rules .book');rules.innerHTML=`<div class="cover"><small>SRD FOUNDATION</small><h1>STORMKEEPER</h1><p>RULES REFERENCE</p></div><h2>Table of Contents</h2><div class="toc">${['Character Creation','Classes','Species','Backgrounds','Equipment','Spellcasting','Conditions'].map(x=>`<button data-chapter="${esc(x)}">${esc(x)}<b>›</b></button>`).join('')}</div><div id="rulesContent" class="book-text"></div>`;rules.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>showRuleChapter(b.dataset.chapter))}
function showRuleChapter(ch){const box=$('rulesContent');if(ch==='Classes'){box.innerHTML=`<button class="btn" onclick="openCatalog()">← Contents</button><h2>Classes</h2>${Object.keys(RULES.classes).map(n=>`<article class="rule-card"><h3>${esc(n)}</h3><p>Hit Die: d${esc(classDef(n).hitDie||8)} • Primary ability: ${esc(classDef(n).primaryAbility||'—')}</p><button class="rule-link" data-class="${esc(n)}">Open class</button></article>`).join('')}`;box.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>{wizardPage=3;show('creator');showDetail('class',b.dataset.class,3,()=>{})})}else if(ch==='Species'){box.innerHTML=`<button class="btn" onclick="openCatalog()">← Contents</button><h2>Species</h2>${Object.keys(RULES.species).map(n=>`<article class="rule-card"><h3>${esc(n)}</h3><p>${esc((RULES.species[n].features||[]).join(', '))}</p></article>`).join('')}`}else if(ch==='Backgrounds'){box.innerHTML=`<button class="btn" onclick="openCatalog()">← Contents</button><h2>Backgrounds</h2>${Object.keys(RULES.backgrounds).map(n=>`<article class="rule-card"><h3>${esc(n)}</h3><p>${esc(RULES.backgrounds[n].feature||'')}</p></article>`).join('')}`}else if(ch==='Conditions'){box.innerHTML=`<button class="btn" onclick="openCatalog()">← Contents</button><h2>Conditions</h2>${(RULES.conditions||[]).map(x=>`<article class="rule-card"><h3>${esc(x)}</h3></article>`).join('')}`}else box.innerHTML=`<button class="btn" onclick="openCatalog()">← Contents</button><h2>${esc(ch)}</h2><p class="muted">This section is ready for the corresponding rules catalog content.</p>`}

$('createBtn').onclick=()=>{initCreator();show('creator')};$('wizardCancel').onclick=()=>show('home');$('homeBtn').onclick=()=>show('home');$('backBtn').onclick=()=>show('home');$('rulesBtn').onclick=async()=>{await openCatalog();show('rules')};$('settingsBtn').onclick=()=>{$('inline').checked=!!state.settings.inlineRules;show('settings')};$('settingsBack').onclick=()=>show('home');$('sheetRulesBtn').onclick=async()=>{await openCatalog();show('rules')};$('deleteCharacterBtn').onclick=()=>{const c=state.characters.find(x=>x.id===openId);if(c&&confirm(`Delete ${c.name||'Unnamed Character'}? This cannot be undone.`)){state.characters=state.characters.filter(x=>x.id!==openId);save();render();show('home');toast('Character deleted')}};$('inline').onchange=e=>{state.settings.inlineRules=e.target.checked;save()};
(async()=>{await loadData();render()})();
